[theme]
base = "light"
primaryColor = "#1F2937"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F9FAFB"
textColor = "#111827"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false